services:
  server:
    image: gitea/gitea:1.19.3
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - gitea
      - proxy
    volumes:
      - ./conf/app.ini:/data/gitea/conf/app.ini
      # - type: bind
      #   source: ./conf/app.ini
      #   target: /data/gitea/conf/app.ini
      - ./conf/public:/data/gitea/public
      - ./conf/templates:/data/gitea/templates
      - ./conf/locale:/data/gitea/options/locale
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.goudham.com`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=myresolver"
      - "traefik.http.services.gitea-frontend.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-service"
      - "traefik.tcp.services.gitea-ssh-service.loadbalancer.server.port=430"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fSs", "localhost:3000/api/healthz"]
      interval: "30s"
      timeout: "5s"
      retries: 3

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: "5s"
      timeout: "5s"
      retries: 3

networks:
  gitea:
    name: "gitea"
    external: false
  proxy:
    external: true
